# TCL File Generated by Component Editor 8.0sp1
# Fri Jan 23 17:08:59 EST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | hex_display_comp "hex_display_comp" v1.0.1
# | null 2009.01.23.17:08:59
# | 
# | 
# | U:/Altera_Monitor_Program/installer/tutorial/example/hw/hex_display_comp/hdl/hex_display_comp.v
# | 
# |    ./hdl/hex_display_comp.v syn, sim
# |    ./hdl/number_to_hex_display.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module hex_display_comp
# | 
set_module_property NAME hex_display_comp
set_module_property VERSION 1.0.1
set_module_property GROUP User
set_module_property DISPLAY_NAME hex_display_comp
set_module_property TOP_LEVEL_HDL_FILE hdl/hex_display_comp.v
set_module_property TOP_LEVEL_HDL_MODULE hex_display_comp
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/hex_display_comp.v {SYNTHESIS SIMULATION}
add_file hdl/number_to_hex_display.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk ptfSchematicName ""

add_interface_port clk clk clk Input 1
add_interface_port clk reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_export
# | 
add_interface avalon_slave_export conduit end

set_interface_property avalon_slave_export ASSOCIATED_CLOCK clk

add_interface_port avalon_slave_export hex0 export Output 7
add_interface_port avalon_slave_export hex1 export Output 7
add_interface_port avalon_slave_export hex2 export Output 7
add_interface_port avalon_slave_export hex3 export Output 7
add_interface_port avalon_slave_export hex4 export Output 7
add_interface_port avalon_slave_export hex5 export Output 7
add_interface_port avalon_slave_export hex6 export Output 7
add_interface_port avalon_slave_export hex7 export Output 7
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave minimumUninterruptedRunLength 1
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave addressSpan 2
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave addressAlignment NATIVE
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave printableDevice false

set_interface_property avalon_slave ASSOCIATED_CLOCK clk

add_interface_port avalon_slave address address Input 1
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input 32
# | 
# +-----------------------------------
